"use server"

import { createClient } from "@/lib/supabase/server"
import { revalidatePath } from "next/cache"
import { getCurrentUser } from "@/lib/get-current-user"
import type {
  PurchaseOrderStatus,
  PurchaseOrderWithItems,
} from "@/types/inventory"

// Real schema: purchase_order_items uses po_id (not purchase_order_id),
// has no created_at. po_number is auto-generated by DB default generate_po_number().
const ITEMS_SELECT =
  "id, product_id, quantity_ordered, unit_cost, notes, products(product_name)"

const PO_SELECT = `
  id, po_number, supplier_id, status, expected_delivery_date, notes, created_by, created_at, updated_at,
  supplier:suppliers(id, name),
  created_by_user:users!purchase_orders_created_by_fkey(name, role),
  items:purchase_order_items!purchase_order_items_po_id_fkey(${ITEMS_SELECT})
`

export async function getPurchaseOrders(params: {
  search?: string
  status?: PurchaseOrderStatus
  supplier_id?: string
  page?: number
  pageSize?: number
}): Promise<{ data: PurchaseOrderWithItems[]; count: number }> {
  const supabase = await createClient()
  const page = params.page ?? 1
  const pageSize = params.pageSize ?? 20
  const from = (page - 1) * pageSize
  const to = from + pageSize - 1

  let query = supabase
    .from("purchase_orders")
    .select(PO_SELECT, { count: "exact" })
    .order("created_at", { ascending: false })

  if (params.search?.trim()) {
    query = query.ilike("po_number", `%${params.search.trim()}%`)
  }

  if (params.status) {
    query = query.eq("status", params.status)
  }

  if (params.supplier_id) {
    query = query.eq("supplier_id", params.supplier_id)
  }

  query = query.range(from, to)

  const { data, error, count } = await query
  if (error) throw new Error(error.message)
  return { data: (data ?? []) as unknown as PurchaseOrderWithItems[], count: count ?? 0 }
}

export async function getPurchaseOrderById(
  id: string,
): Promise<PurchaseOrderWithItems | null> {
  const supabase = await createClient()
  const { data, error } = await supabase
    .from("purchase_orders")
    .select(PO_SELECT)
    .eq("id", id)
    .maybeSingle()
  if (error) throw new Error(error.message)
  return data as unknown as PurchaseOrderWithItems | null
}

export async function createPurchaseOrder(data: {
  supplier_id: string | null
  expected_delivery_date: string | null
  notes: string | null
  items: {
    product_id: string
    quantity_ordered: number
    unit_cost: number
    notes: string | null
  }[]
}): Promise<{ success: boolean; id?: string; error?: string }> {
  try {
    const currentUser = await getCurrentUser()
    if (currentUser.role === "pharmacy_assistant") {
      return { success: false, error: "Unauthorized: insufficient permissions" }
    }

    if (!data.items || data.items.length === 0) {
      return { success: false, error: "At least one item is required" }
    }

    const supabase = await createClient()

    // po_number is auto-generated by DB default generate_po_number()
    const { data: po, error: poError } = await supabase
      .from("purchase_orders")
      .insert({
        supplier_id: data.supplier_id,
        expected_delivery_date: data.expected_delivery_date,
        notes: data.notes,
        status: "draft",
        created_by: currentUser.id,
      })
      .select("id, po_number")
      .single()

    if (poError) return { success: false, error: poError.message }

    const { error: itemsError } = await supabase
      .from("purchase_order_items")
      .insert(
        data.items.map(item => ({
          po_id: po.id,
          product_id: item.product_id,
          quantity_ordered: item.quantity_ordered,
          unit_cost: item.unit_cost,
          notes: item.notes,
        })),
      )

    if (itemsError) return { success: false, error: itemsError.message }

    revalidatePath("/admin/purchase-orders")
    return { success: true, id: po.id }
  } catch (err) {
    return { success: false, error: err instanceof Error ? err.message : "Unknown error" }
  }
}

export async function updatePurchaseOrder(
  id: string,
  data: {
    supplier_id: string | null
    expected_delivery_date: string | null
    notes: string | null
    items: {
      product_id: string
      quantity_ordered: number
      unit_cost: number
      notes: string | null
    }[]
  },
): Promise<{ success: boolean; error?: string }> {
  try {
    const currentUser = await getCurrentUser()
    if (currentUser.role === "pharmacy_assistant") {
      return { success: false, error: "Unauthorized: insufficient permissions" }
    }

    const supabase = await createClient()

    const { data: existing, error: fetchError } = await supabase
      .from("purchase_orders")
      .select("status")
      .eq("id", id)
      .single()

    if (fetchError) return { success: false, error: fetchError.message }
    if (existing.status !== "draft") {
      return { success: false, error: "Only draft purchase orders can be edited" }
    }

    const { error: poError } = await supabase
      .from("purchase_orders")
      .update({
        supplier_id: data.supplier_id,
        expected_delivery_date: data.expected_delivery_date,
        notes: data.notes,
        updated_at: new Date().toISOString(),
      })
      .eq("id", id)

    if (poError) return { success: false, error: poError.message }

    const { error: deleteError } = await supabase
      .from("purchase_order_items")
      .delete()
      .eq("po_id", id)

    if (deleteError) return { success: false, error: deleteError.message }

    const { error: itemsError } = await supabase
      .from("purchase_order_items")
      .insert(
        data.items.map(item => ({
          po_id: id,
          product_id: item.product_id,
          quantity_ordered: item.quantity_ordered,
          unit_cost: item.unit_cost,
          notes: item.notes,
        })),
      )

    if (itemsError) return { success: false, error: itemsError.message }

    revalidatePath("/admin/purchase-orders")
    return { success: true }
  } catch (err) {
    return { success: false, error: err instanceof Error ? err.message : "Unknown error" }
  }
}

export async function submitPurchaseOrder(
  id: string,
): Promise<{ success: boolean; error?: string }> {
  try {
    const currentUser = await getCurrentUser()
    if (currentUser.role === "pharmacy_assistant") {
      return { success: false, error: "Unauthorized: insufficient permissions" }
    }

    const supabase = await createClient()

    const { data: existing, error: fetchError } = await supabase
      .from("purchase_orders")
      .select("status")
      .eq("id", id)
      .single()

    if (fetchError) return { success: false, error: fetchError.message }
    if (existing.status !== "draft") {
      return { success: false, error: "Only draft purchase orders can be submitted" }
    }

    const { error } = await supabase
      .from("purchase_orders")
      .update({ status: "submitted", updated_at: new Date().toISOString() })
      .eq("id", id)

    if (error) return { success: false, error: error.message }

    revalidatePath("/admin/purchase-orders")
    return { success: true }
  } catch (err) {
    return { success: false, error: err instanceof Error ? err.message : "Unknown error" }
  }
}

export async function cancelPurchaseOrder(
  id: string,
): Promise<{ success: boolean; error?: string }> {
  try {
    const currentUser = await getCurrentUser()
    if (currentUser.role !== "admin") {
      return { success: false, error: "Unauthorized: Admin access required" }
    }

    const supabase = await createClient()

    const { data: existing, error: fetchError } = await supabase
      .from("purchase_orders")
      .select("status")
      .eq("id", id)
      .single()

    if (fetchError) return { success: false, error: fetchError.message }
    if (existing.status === "received" || existing.status === "cancelled") {
      return {
        success: false,
        error: `Cannot cancel a purchase order with status '${existing.status}'`,
      }
    }

    const { error } = await supabase
      .from("purchase_orders")
      .update({ status: "cancelled", updated_at: new Date().toISOString() })
      .eq("id", id)

    if (error) return { success: false, error: error.message }

    revalidatePath("/admin/purchase-orders")
    return { success: true }
  } catch (err) {
    return { success: false, error: err instanceof Error ? err.message : "Unknown error" }
  }
}
